//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Monster.Acumatica.BankImportApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ScreenSoap", Namespace="http://www.acumatica.com/generic/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Filter[]))]
    public partial class Screen : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetScenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetBusinessDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetLocaleNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchemaModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500ClearOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500GetProcessStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500GetSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500SetSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500ImportOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500ExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback CA306500SubmitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Screen() {
            this.Url = global::Monster.Acumatica.Properties.Settings.Default.Monster_Acumatica_BankImportApi_Screen;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetScenarioCompletedEventHandler GetScenarioCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event SetBusinessDateCompletedEventHandler SetBusinessDateCompleted;
        
        /// <remarks/>
        public event SetLocaleNameCompletedEventHandler SetLocaleNameCompleted;
        
        /// <remarks/>
        public event SetSchemaModeCompletedEventHandler SetSchemaModeCompleted;
        
        /// <remarks/>
        public event CA306500ClearCompletedEventHandler CA306500ClearCompleted;
        
        /// <remarks/>
        public event CA306500GetProcessStatusCompletedEventHandler CA306500GetProcessStatusCompleted;
        
        /// <remarks/>
        public event CA306500GetSchemaCompletedEventHandler CA306500GetSchemaCompleted;
        
        /// <remarks/>
        public event CA306500SetSchemaCompletedEventHandler CA306500SetSchemaCompleted;
        
        /// <remarks/>
        public event CA306500ImportCompletedEventHandler CA306500ImportCompleted;
        
        /// <remarks/>
        public event CA306500ExportCompletedEventHandler CA306500ExportCompleted;
        
        /// <remarks/>
        public event CA306500SubmitCompletedEventHandler CA306500SubmitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/GetScenario", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Command[] GetScenario(string scenario) {
            object[] results = this.Invoke("GetScenario", new object[] {
                        scenario});
            return ((Command[])(results[0]));
        }
        
        /// <remarks/>
        public void GetScenarioAsync(string scenario) {
            this.GetScenarioAsync(scenario, null);
        }
        
        /// <remarks/>
        public void GetScenarioAsync(string scenario, object userState) {
            if ((this.GetScenarioOperationCompleted == null)) {
                this.GetScenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScenarioOperationCompleted);
            }
            this.InvokeAsync("GetScenario", new object[] {
                        scenario}, this.GetScenarioOperationCompleted, userState);
        }
        
        private void OnGetScenarioOperationCompleted(object arg) {
            if ((this.GetScenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScenarioCompleted(this, new GetScenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/Login", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginResult Login(string name, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        name,
                        password});
            return ((LoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string name, string password) {
            this.LoginAsync(name, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string name, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        name,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/Logout", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout() {
            this.Invoke("Logout", new object[0]);
        }
        
        /// <remarks/>
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[0], this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/SetBusinessDate", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetBusinessDate(System.DateTime date) {
            this.Invoke("SetBusinessDate", new object[] {
                        date});
        }
        
        /// <remarks/>
        public void SetBusinessDateAsync(System.DateTime date) {
            this.SetBusinessDateAsync(date, null);
        }
        
        /// <remarks/>
        public void SetBusinessDateAsync(System.DateTime date, object userState) {
            if ((this.SetBusinessDateOperationCompleted == null)) {
                this.SetBusinessDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetBusinessDateOperationCompleted);
            }
            this.InvokeAsync("SetBusinessDate", new object[] {
                        date}, this.SetBusinessDateOperationCompleted, userState);
        }
        
        private void OnSetBusinessDateOperationCompleted(object arg) {
            if ((this.SetBusinessDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetBusinessDateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/SetLocaleName", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetLocaleName(string localeName) {
            this.Invoke("SetLocaleName", new object[] {
                        localeName});
        }
        
        /// <remarks/>
        public void SetLocaleNameAsync(string localeName) {
            this.SetLocaleNameAsync(localeName, null);
        }
        
        /// <remarks/>
        public void SetLocaleNameAsync(string localeName, object userState) {
            if ((this.SetLocaleNameOperationCompleted == null)) {
                this.SetLocaleNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLocaleNameOperationCompleted);
            }
            this.InvokeAsync("SetLocaleName", new object[] {
                        localeName}, this.SetLocaleNameOperationCompleted, userState);
        }
        
        private void OnSetLocaleNameOperationCompleted(object arg) {
            if ((this.SetLocaleNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLocaleNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/SetSchemaMode", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSchemaMode(SchemaMode mode) {
            this.Invoke("SetSchemaMode", new object[] {
                        mode});
        }
        
        /// <remarks/>
        public void SetSchemaModeAsync(SchemaMode mode) {
            this.SetSchemaModeAsync(mode, null);
        }
        
        /// <remarks/>
        public void SetSchemaModeAsync(SchemaMode mode, object userState) {
            if ((this.SetSchemaModeOperationCompleted == null)) {
                this.SetSchemaModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchemaModeOperationCompleted);
            }
            this.InvokeAsync("SetSchemaMode", new object[] {
                        mode}, this.SetSchemaModeOperationCompleted, userState);
        }
        
        private void OnSetSchemaModeOperationCompleted(object arg) {
            if ((this.SetSchemaModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchemaModeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/Clear", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CA306500Clear() {
            this.Invoke("CA306500Clear", new object[0]);
        }
        
        /// <remarks/>
        public void CA306500ClearAsync() {
            this.CA306500ClearAsync(null);
        }
        
        /// <remarks/>
        public void CA306500ClearAsync(object userState) {
            if ((this.CA306500ClearOperationCompleted == null)) {
                this.CA306500ClearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500ClearOperationCompleted);
            }
            this.InvokeAsync("CA306500Clear", new object[0], this.CA306500ClearOperationCompleted, userState);
        }
        
        private void OnCA306500ClearOperationCompleted(object arg) {
            if ((this.CA306500ClearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500ClearCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/GetProcessStatus", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProcessStatusResult")]
        public ProcessResult CA306500GetProcessStatus() {
            object[] results = this.Invoke("CA306500GetProcessStatus", new object[0]);
            return ((ProcessResult)(results[0]));
        }
        
        /// <remarks/>
        public void CA306500GetProcessStatusAsync() {
            this.CA306500GetProcessStatusAsync(null);
        }
        
        /// <remarks/>
        public void CA306500GetProcessStatusAsync(object userState) {
            if ((this.CA306500GetProcessStatusOperationCompleted == null)) {
                this.CA306500GetProcessStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500GetProcessStatusOperationCompleted);
            }
            this.InvokeAsync("CA306500GetProcessStatus", new object[0], this.CA306500GetProcessStatusOperationCompleted, userState);
        }
        
        private void OnCA306500GetProcessStatusOperationCompleted(object arg) {
            if ((this.CA306500GetProcessStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500GetProcessStatusCompleted(this, new CA306500GetProcessStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/GetSchema", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetSchemaResult")]
        public CA306500Content CA306500GetSchema() {
            object[] results = this.Invoke("CA306500GetSchema", new object[0]);
            return ((CA306500Content)(results[0]));
        }
        
        /// <remarks/>
        public void CA306500GetSchemaAsync() {
            this.CA306500GetSchemaAsync(null);
        }
        
        /// <remarks/>
        public void CA306500GetSchemaAsync(object userState) {
            if ((this.CA306500GetSchemaOperationCompleted == null)) {
                this.CA306500GetSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500GetSchemaOperationCompleted);
            }
            this.InvokeAsync("CA306500GetSchema", new object[0], this.CA306500GetSchemaOperationCompleted, userState);
        }
        
        private void OnCA306500GetSchemaOperationCompleted(object arg) {
            if ((this.CA306500GetSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500GetSchemaCompleted(this, new CA306500GetSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/SetSchema", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CA306500SetSchema(CA306500Content schema) {
            this.Invoke("CA306500SetSchema", new object[] {
                        schema});
        }
        
        /// <remarks/>
        public void CA306500SetSchemaAsync(CA306500Content schema) {
            this.CA306500SetSchemaAsync(schema, null);
        }
        
        /// <remarks/>
        public void CA306500SetSchemaAsync(CA306500Content schema, object userState) {
            if ((this.CA306500SetSchemaOperationCompleted == null)) {
                this.CA306500SetSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500SetSchemaOperationCompleted);
            }
            this.InvokeAsync("CA306500SetSchema", new object[] {
                        schema}, this.CA306500SetSchemaOperationCompleted, userState);
        }
        
        private void OnCA306500SetSchemaOperationCompleted(object arg) {
            if ((this.CA306500SetSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500SetSchemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/Import", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ImportResult")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ImportResult")]
        public CA306500ImportResult[] CA306500Import(Command[] commands, Filter[] filters, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            object[] results = this.Invoke("CA306500Import", new object[] {
                        commands,
                        filters,
                        data,
                        includedHeaders,
                        breakOnError,
                        breakOnIncorrectTarget});
            return ((CA306500ImportResult[])(results[0]));
        }
        
        /// <remarks/>
        public void CA306500ImportAsync(Command[] commands, Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            this.CA306500ImportAsync(commands, filters, data, includedHeaders, breakOnError, breakOnIncorrectTarget, null);
        }
        
        /// <remarks/>
        public void CA306500ImportAsync(Command[] commands, Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget, object userState) {
            if ((this.CA306500ImportOperationCompleted == null)) {
                this.CA306500ImportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500ImportOperationCompleted);
            }
            this.InvokeAsync("CA306500Import", new object[] {
                        commands,
                        filters,
                        data,
                        includedHeaders,
                        breakOnError,
                        breakOnIncorrectTarget}, this.CA306500ImportOperationCompleted, userState);
        }
        
        private void OnCA306500ImportOperationCompleted(object arg) {
            if ((this.CA306500ImportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500ImportCompleted(this, new CA306500ImportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/Export", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ExportResult")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] CA306500Export(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            object[] results = this.Invoke("CA306500Export", new object[] {
                        commands,
                        filters,
                        topCount,
                        includeHeaders,
                        breakOnError});
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void CA306500ExportAsync(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            this.CA306500ExportAsync(commands, filters, topCount, includeHeaders, breakOnError, null);
        }
        
        /// <remarks/>
        public void CA306500ExportAsync(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError, object userState) {
            if ((this.CA306500ExportOperationCompleted == null)) {
                this.CA306500ExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500ExportOperationCompleted);
            }
            this.InvokeAsync("CA306500Export", new object[] {
                        commands,
                        filters,
                        topCount,
                        includeHeaders,
                        breakOnError}, this.CA306500ExportOperationCompleted, userState);
        }
        
        private void OnCA306500ExportOperationCompleted(object arg) {
            if ((this.CA306500ExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500ExportCompleted(this, new CA306500ExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/CA306500/Submit", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("SubmitResult")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Content")]
        public CA306500Content[] CA306500Submit(Command[] commands) {
            object[] results = this.Invoke("CA306500Submit", new object[] {
                        commands});
            return ((CA306500Content[])(results[0]));
        }
        
        /// <remarks/>
        public void CA306500SubmitAsync(Command[] commands) {
            this.CA306500SubmitAsync(commands, null);
        }
        
        /// <remarks/>
        public void CA306500SubmitAsync(Command[] commands, object userState) {
            if ((this.CA306500SubmitOperationCompleted == null)) {
                this.CA306500SubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCA306500SubmitOperationCompleted);
            }
            this.InvokeAsync("CA306500Submit", new object[] {
                        commands}, this.CA306500SubmitOperationCompleted, userState);
        }
        
        private void OnCA306500SubmitOperationCompleted(object arg) {
            if ((this.CA306500SubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CA306500SubmitCompleted(this, new CA306500SubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Answer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Action))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Key))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EveryValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Command {
        
        private string fieldNameField;
        
        private string objectNameField;
        
        private string valueField;
        
        private bool commitField;
        
        private bool ignoreErrorField;
        
        private Command linkedCommandField;
        
        private ElementDescriptor descriptorField;
        
        public Command() {
            this.commitField = false;
            this.ignoreErrorField = false;
        }
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Commit {
            get {
                return this.commitField;
            }
            set {
                this.commitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreError {
            get {
                return this.ignoreErrorField;
            }
            set {
                this.ignoreErrorField = value;
            }
        }
        
        /// <remarks/>
        public Command LinkedCommand {
            get {
                return this.linkedCommandField;
            }
            set {
                this.linkedCommandField = value;
            }
        }
        
        /// <remarks/>
        public ElementDescriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class ElementDescriptor {
        
        private string displayNameField;
        
        private bool isDisabledField;
        
        private bool isRequiredField;
        
        private ElementTypes elementTypeField;
        
        private int lengthLimitField;
        
        private string inputMaskField;
        
        private string displayRulesField;
        
        private string[] allowedValuesField;
        
        public ElementDescriptor() {
            this.isDisabledField = false;
            this.isRequiredField = false;
            this.elementTypeField = ElementTypes.String;
            this.lengthLimitField = 0;
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDisabled {
            get {
                return this.isDisabledField;
            }
            set {
                this.isDisabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ElementTypes.String)]
        public ElementTypes ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int LengthLimit {
            get {
                return this.lengthLimitField;
            }
            set {
                this.lengthLimitField = value;
            }
        }
        
        /// <remarks/>
        public string InputMask {
            get {
                return this.inputMaskField;
            }
            set {
                this.inputMaskField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayRules {
            get {
                return this.displayRulesField;
            }
            set {
                this.displayRulesField = value;
            }
        }
        
        /// <remarks/>
        public string[] AllowedValues {
            get {
                return this.allowedValuesField;
            }
            set {
                this.allowedValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum ElementTypes {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        AsciiString,
        
        /// <remarks/>
        StringSelector,
        
        /// <remarks/>
        ExplicitSelector,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Option,
        
        /// <remarks/>
        WideOption,
        
        /// <remarks/>
        Calendar,
        
        /// <remarks/>
        Action,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500ImportResult {
        
        private bool processedField;
        
        private string errorField;
        
        private CA306500PrimaryKey keysField;
        
        /// <remarks/>
        public bool Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public CA306500PrimaryKey Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500PrimaryKey {
        
        private Value cashAccountField;
        
        private Value referenceNbrField;
        
        /// <remarks/>
        public Value CashAccount {
            get {
                return this.cashAccountField;
            }
            set {
                this.cashAccountField = value;
            }
        }
        
        /// <remarks/>
        public Value ReferenceNbr {
            get {
                return this.referenceNbrField;
            }
            set {
                this.referenceNbrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Value : Field {
        
        private string messageField;
        
        private bool isErrorField;
        
        public Value() {
            this.isErrorField = false;
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Field : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Attachment : Field {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Filter {
        
        private Field fieldField;
        
        private FilterCondition conditionField;
        
        private object valueField;
        
        private object value2Field;
        
        private int openBracketsField;
        
        private int closeBracketsField;
        
        private FilterOperator operatorField;
        
        /// <remarks/>
        public Field Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public FilterCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public object Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
            }
        }
        
        /// <remarks/>
        public int OpenBrackets {
            get {
                return this.openBracketsField;
            }
            set {
                this.openBracketsField = value;
            }
        }
        
        /// <remarks/>
        public int CloseBrackets {
            get {
                return this.closeBracketsField;
            }
            set {
                this.closeBracketsField = value;
            }
        }
        
        /// <remarks/>
        public FilterOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum FilterCondition {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Contain,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        NotContain,
        
        /// <remarks/>
        Between,
        
        /// <remarks/>
        IsNull,
        
        /// <remarks/>
        IsNotNull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum FilterOperator {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500DetailsServiceCommands {
        
        private NewRow newRowField;
        
        private RowNumber rowNumberField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public NewRow NewRow {
            get {
                return this.newRowField;
            }
            set {
                this.newRowField = value;
            }
        }
        
        /// <remarks/>
        public RowNumber RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class NewRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class RowNumber : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class DeleteRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Answer : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500Details {
        
        private string displayNameField;
        
        private Field documentMatchedField;
        
        private Field processedField;
        
        private Field hiddenField;
        
        private Field extTranIDField;
        
        private Field extRefNbrField;
        
        private Field tranDateField;
        
        private Field tranDescField;
        
        private Field tranCodeField;
        
        private Field receiptField;
        
        private Field disbursementField;
        
        private Field invoiceNbrField;
        
        private Field appliedRuleField;
        
        private Field payeeNameField;
        
        private Field entryTypeIDField;
        
        private Field paymentMethodField;
        
        private Field businessAccountField;
        
        private Field businessAccountNameField;
        
        private Field moduleField;
        
        private Field locationField;
        
        private Field noteTextField;
        
        private CA306500DetailsServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field DocumentMatched {
            get {
                return this.documentMatchedField;
            }
            set {
                this.documentMatchedField = value;
            }
        }
        
        /// <remarks/>
        public Field Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        public Field Hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
            }
        }
        
        /// <remarks/>
        public Field ExtTranID {
            get {
                return this.extTranIDField;
            }
            set {
                this.extTranIDField = value;
            }
        }
        
        /// <remarks/>
        public Field ExtRefNbr {
            get {
                return this.extRefNbrField;
            }
            set {
                this.extRefNbrField = value;
            }
        }
        
        /// <remarks/>
        public Field TranDate {
            get {
                return this.tranDateField;
            }
            set {
                this.tranDateField = value;
            }
        }
        
        /// <remarks/>
        public Field TranDesc {
            get {
                return this.tranDescField;
            }
            set {
                this.tranDescField = value;
            }
        }
        
        /// <remarks/>
        public Field TranCode {
            get {
                return this.tranCodeField;
            }
            set {
                this.tranCodeField = value;
            }
        }
        
        /// <remarks/>
        public Field Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public Field Disbursement {
            get {
                return this.disbursementField;
            }
            set {
                this.disbursementField = value;
            }
        }
        
        /// <remarks/>
        public Field InvoiceNbr {
            get {
                return this.invoiceNbrField;
            }
            set {
                this.invoiceNbrField = value;
            }
        }
        
        /// <remarks/>
        public Field AppliedRule {
            get {
                return this.appliedRuleField;
            }
            set {
                this.appliedRuleField = value;
            }
        }
        
        /// <remarks/>
        public Field PayeeName {
            get {
                return this.payeeNameField;
            }
            set {
                this.payeeNameField = value;
            }
        }
        
        /// <remarks/>
        public Field EntryTypeID {
            get {
                return this.entryTypeIDField;
            }
            set {
                this.entryTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public Field PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public Field BusinessAccount {
            get {
                return this.businessAccountField;
            }
            set {
                this.businessAccountField = value;
            }
        }
        
        /// <remarks/>
        public Field BusinessAccountName {
            get {
                return this.businessAccountNameField;
            }
            set {
                this.businessAccountNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        public Field Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public Field NoteText {
            get {
                return this.noteTextField;
            }
            set {
                this.noteTextField = value;
            }
        }
        
        /// <remarks/>
        public CA306500DetailsServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500CashAccountServiceCommands {
        
        private Key keyCashAccountField;
        
        private EveryValue everyCashAccountField;
        
        private Key keyReferenceNbrField;
        
        private EveryValue everyReferenceNbrField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public Key KeyCashAccount {
            get {
                return this.keyCashAccountField;
            }
            set {
                this.keyCashAccountField = value;
            }
        }
        
        /// <remarks/>
        public EveryValue EveryCashAccount {
            get {
                return this.everyCashAccountField;
            }
            set {
                this.everyCashAccountField = value;
            }
        }
        
        /// <remarks/>
        public Key KeyReferenceNbr {
            get {
                return this.keyReferenceNbrField;
            }
            set {
                this.keyReferenceNbrField = value;
            }
        }
        
        /// <remarks/>
        public EveryValue EveryReferenceNbr {
            get {
                return this.everyReferenceNbrField;
            }
            set {
                this.everyReferenceNbrField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Key : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class EveryValue : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500CashAccount {
        
        private string displayNameField;
        
        private Field cashAccountField;
        
        private Field referenceNbrField;
        
        private Field statementDateField;
        
        private Field startBalanceDateField;
        
        private Field endBalanceDateField;
        
        private Field beginningBalanceField;
        
        private Field endingBalanceField;
        
        private Field calculatedBalanceField;
        
        private CA306500CashAccountServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field CashAccount {
            get {
                return this.cashAccountField;
            }
            set {
                this.cashAccountField = value;
            }
        }
        
        /// <remarks/>
        public Field ReferenceNbr {
            get {
                return this.referenceNbrField;
            }
            set {
                this.referenceNbrField = value;
            }
        }
        
        /// <remarks/>
        public Field StatementDate {
            get {
                return this.statementDateField;
            }
            set {
                this.statementDateField = value;
            }
        }
        
        /// <remarks/>
        public Field StartBalanceDate {
            get {
                return this.startBalanceDateField;
            }
            set {
                this.startBalanceDateField = value;
            }
        }
        
        /// <remarks/>
        public Field EndBalanceDate {
            get {
                return this.endBalanceDateField;
            }
            set {
                this.endBalanceDateField = value;
            }
        }
        
        /// <remarks/>
        public Field BeginningBalance {
            get {
                return this.beginningBalanceField;
            }
            set {
                this.beginningBalanceField = value;
            }
        }
        
        /// <remarks/>
        public Field EndingBalance {
            get {
                return this.endingBalanceField;
            }
            set {
                this.endingBalanceField = value;
            }
        }
        
        /// <remarks/>
        public Field CalculatedBalance {
            get {
                return this.calculatedBalanceField;
            }
            set {
                this.calculatedBalanceField = value;
            }
        }
        
        /// <remarks/>
        public CA306500CashAccountServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500Actions {
        
        private Action cancelCloseToListField;
        
        private Action saveCloseToListField;
        
        private Action saveField;
        
        private Action cancelField;
        
        private Action insertField;
        
        private Action deleteField;
        
        private Action copyDocumentCopyPasteField;
        
        private Action pasteDocumentCopyPasteField;
        
        private Action saveTemplateCopyPasteField;
        
        private Action firstField;
        
        private Action previousField;
        
        private Action nextField;
        
        private Action lastField;
        
        private Action uploadFileField;
        
        private Action unhideField;
        
        private Action unmatchField;
        
        private Action viewDocField;
        
        private Action resetListNavigationField;
        
        private Action saveLocField;
        
        /// <remarks/>
        public Action CancelCloseToList {
            get {
                return this.cancelCloseToListField;
            }
            set {
                this.cancelCloseToListField = value;
            }
        }
        
        /// <remarks/>
        public Action SaveCloseToList {
            get {
                return this.saveCloseToListField;
            }
            set {
                this.saveCloseToListField = value;
            }
        }
        
        /// <remarks/>
        public Action Save {
            get {
                return this.saveField;
            }
            set {
                this.saveField = value;
            }
        }
        
        /// <remarks/>
        public Action Cancel {
            get {
                return this.cancelField;
            }
            set {
                this.cancelField = value;
            }
        }
        
        /// <remarks/>
        public Action Insert {
            get {
                return this.insertField;
            }
            set {
                this.insertField = value;
            }
        }
        
        /// <remarks/>
        public Action Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public Action CopyDocumentCopyPaste {
            get {
                return this.copyDocumentCopyPasteField;
            }
            set {
                this.copyDocumentCopyPasteField = value;
            }
        }
        
        /// <remarks/>
        public Action PasteDocumentCopyPaste {
            get {
                return this.pasteDocumentCopyPasteField;
            }
            set {
                this.pasteDocumentCopyPasteField = value;
            }
        }
        
        /// <remarks/>
        public Action SaveTemplateCopyPaste {
            get {
                return this.saveTemplateCopyPasteField;
            }
            set {
                this.saveTemplateCopyPasteField = value;
            }
        }
        
        /// <remarks/>
        public Action First {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        public Action Previous {
            get {
                return this.previousField;
            }
            set {
                this.previousField = value;
            }
        }
        
        /// <remarks/>
        public Action Next {
            get {
                return this.nextField;
            }
            set {
                this.nextField = value;
            }
        }
        
        /// <remarks/>
        public Action Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        public Action UploadFile {
            get {
                return this.uploadFileField;
            }
            set {
                this.uploadFileField = value;
            }
        }
        
        /// <remarks/>
        public Action Unhide {
            get {
                return this.unhideField;
            }
            set {
                this.unhideField = value;
            }
        }
        
        /// <remarks/>
        public Action Unmatch {
            get {
                return this.unmatchField;
            }
            set {
                this.unmatchField = value;
            }
        }
        
        /// <remarks/>
        public Action ViewDoc {
            get {
                return this.viewDocField;
            }
            set {
                this.viewDocField = value;
            }
        }
        
        /// <remarks/>
        public Action ResetListNavigation {
            get {
                return this.resetListNavigationField;
            }
            set {
                this.resetListNavigationField = value;
            }
        }
        
        /// <remarks/>
        public Action SaveLoc {
            get {
                return this.saveLocField;
            }
            set {
                this.saveLocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Action : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class CA306500Content {
        
        private CA306500Actions actionsField;
        
        private CA306500CashAccount cashAccountField;
        
        private CA306500Details detailsField;
        
        /// <remarks/>
        public CA306500Actions Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        public CA306500CashAccount CashAccount {
            get {
                return this.cashAccountField;
            }
            set {
                this.cashAccountField = value;
            }
        }
        
        /// <remarks/>
        public CA306500Details Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class ProcessResult {
        
        private ProcessStatus statusField;
        
        private int secondsField;
        
        private string messageField;
        
        /// <remarks/>
        public ProcessStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum ProcessStatus {
        
        /// <remarks/>
        NotExists,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class LoginResult {
        
        private ErrorCode codeField;
        
        private string messageField;
        
        private string sessionField;
        
        /// <remarks/>
        public ErrorCode Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum ErrorCode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        INVALID_CREDENTIALS,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        INVALID_API_VERSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Parameter : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum SchemaMode {
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Detailed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetScenarioCompletedEventHandler(object sender, GetScenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Command[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Command[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetBusinessDateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetLocaleNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetSchemaModeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500ClearCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500GetProcessStatusCompletedEventHandler(object sender, CA306500GetProcessStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CA306500GetProcessStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CA306500GetProcessStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcessResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcessResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500GetSchemaCompletedEventHandler(object sender, CA306500GetSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CA306500GetSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CA306500GetSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CA306500Content Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CA306500Content)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500SetSchemaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500ImportCompletedEventHandler(object sender, CA306500ImportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CA306500ImportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CA306500ImportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CA306500ImportResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CA306500ImportResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500ExportCompletedEventHandler(object sender, CA306500ExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CA306500ExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CA306500ExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CA306500SubmitCompletedEventHandler(object sender, CA306500SubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CA306500SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CA306500SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CA306500Content[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CA306500Content[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591