USE master

/** This script will clear all open connections to ProfitWise **/

ALTER DATABASE AcuInst2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
ALTER DATABASE AcuInst2 SET MULTI_USER


ALTER DATABASE Monster0001 SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
ALTER DATABASE Monster0001 SET MULTI_USER


